from PyQt5 import QtGui, QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget

class Hook_Collection_View(QWidget):

    def __init__(self, parent=None):
        QWidget.__init__(self, parent=parent)
        self.setObjectName("hook_collection_page")
        self.hook_collection_frame = QtWidgets.QFrame(self)
        self.hook_collection_frame.setGeometry(QtCore.QRect(0, 0, 881, 651))
        self.hook_collection_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hook_collection_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hook_collection_frame.setObjectName("hook_collection_frame")
        self.hook_collection_mframe = QtWidgets.QFrame(self.hook_collection_frame)
        self.hook_collection_mframe.setGeometry(QtCore.QRect(-10, 50, 871, 631))
        self.hook_collection_mframe.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hook_collection_mframe.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hook_collection_mframe.setObjectName("hook_collection_mframe")
        self.hook_collection_properties = QtWidgets.QFrame(self.hook_collection_mframe)
        self.hook_collection_properties.setGeometry(QtCore.QRect(50, 100, 821, 501))
        self.hook_collection_properties.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.hook_collection_properties.setFrameShadow(QtWidgets.QFrame.Raised)
        self.hook_collection_properties.setObjectName("hook_collection_properties")
        self.collection_properties_title = QtWidgets.QLabel(self.hook_collection_properties)
        self.collection_properties_title.setGeometry(QtCore.QRect(0, 0, 741, 51))
        self.collection_properties_title.setStyleSheet("background-color: rgb(75, 151, 226);\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"")
        self.collection_properties_title.setObjectName("collection_properties_title")
        self.hook_collection_table = QtWidgets.QTableWidget(self.hook_collection_properties)
        self.hook_collection_table.setGeometry(QtCore.QRect(0, 50, 741, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hook_collection_table.sizePolicy().hasHeightForWidth())
        self.hook_collection_table.setSizePolicy(sizePolicy)
        self.hook_collection_table.setMinimumSize(QtCore.QSize(741, 0))
        self.hook_collection_table.setMaximumSize(QtCore.QSize(741, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.hook_collection_table.setFont(font)
        self.hook_collection_table.setStyleSheet("gridline-color: white;\n"
"border-right-color: white;\n"
"border-left-color: white;\n"
"\n"
"")
        self.hook_collection_table.setLineWidth(1)
        self.hook_collection_table.setMidLineWidth(1)
        self.hook_collection_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.hook_collection_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.hook_collection_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.hook_collection_table.setEditTriggers(QtWidgets.QAbstractItemView.AnyKeyPressed|QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.hook_collection_table.setShowGrid(True)
        self.hook_collection_table.setGridStyle(QtCore.Qt.DotLine)
        self.hook_collection_table.setCornerButtonEnabled(True)
        self.hook_collection_table.setRowCount(6)
        self.hook_collection_table.setObjectName("hook_collection_table")
        self.hook_collection_table.setColumnCount(4)
        item = QtWidgets.QTableWidgetItem()
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("./Resources/CircularButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon1)
        self.hook_collection_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("./Resources/CircularButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon2)
        self.hook_collection_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon2)
        self.hook_collection_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon2)
        self.hook_collection_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon2)
        self.hook_collection_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon2)
        self.hook_collection_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        item.setFont(font)
        self.hook_collection_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        item.setFont(font)
        self.hook_collection_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        item.setFont(font)
        self.hook_collection_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        item.setFont(font)
        self.hook_collection_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hook_collection_table.setItem(1, 0, item)
        self.hook_collection_table.horizontalHeader().setVisible(False)
        self.hook_collection_table.horizontalHeader().setCascadingSectionResizes(False)
        self.hook_collection_table.horizontalHeader().setDefaultSectionSize(150)
        self.hook_collection_table.horizontalHeader().setSortIndicatorShown(False)
        self.hook_collection_table.horizontalHeader().setStretchLastSection(True)
        self.hook_collection_table.verticalHeader().setVisible(False)
        self.hook_collection_table.verticalHeader().setCascadingSectionResizes(False)
        self.hook_collection_table.verticalHeader().setDefaultSectionSize(40)
        self.hook_collection_table.verticalHeader().setHighlightSections(True)
        self.hook_collection_table.verticalHeader().setMinimumSectionSize(25)
        self.hook_collection_table.verticalHeader().setSortIndicatorShown(True)
        self.hook_collection_table.verticalHeader().setStretchLastSection(False)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.hook_collection_mframe)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(40, 30, 821, 39))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.delete_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.delete_button.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(232, 232, 232)")
        self.delete_button.setObjectName("delete_button")
        self.gridLayout_2.addWidget(self.delete_button, 0, 2, 1, 1)
        self.add_new_collection_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.add_new_collection_button.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(232, 232, 232)")
        self.add_new_collection_button.setObjectName("add_new_collection_button")
        self.gridLayout_2.addWidget(self.add_new_collection_button, 0, 0, 1, 1)
        self.edit_button = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.edit_button.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(232, 232, 232)")
        self.edit_button.setObjectName("edit_button")
        self.gridLayout_2.addWidget(self.edit_button, 0, 1, 1, 1)
        self.hook_collection_search = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.hook_collection_search.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";")
        self.hook_collection_search.setObjectName("hook_collection_search")
        self.gridLayout_2.addWidget(self.hook_collection_search, 0, 4, 1, 1)
        self.hook_collection_search_input = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.hook_collection_search_input.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";\n"
"color: rgb(179, 179, 179);\n"
"")
        self.hook_collection_search_input.setObjectName("hook_collection_search_input")
        self.gridLayout_2.addWidget(self.hook_collection_search_input, 0, 5, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem3, 0, 3, 1, 1)
        self.hook_collection_title = QtWidgets.QLabel(self.hook_collection_frame)
        self.hook_collection_title.setGeometry(QtCore.QRect(0, 0, 881, 51))
        self.hook_collection_title.setStyleSheet("background-color: rgb(75, 151, 226);\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"")
        self.hook_collection_title.setObjectName("hook_collection_title")

    def retranslateUI(self):
        _translate = QtCore.QCoreApplication.translate
        self.collection_properties_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Hook Collection Properties</span></p></body></html>"))
        self.hook_collection_table.setSortingEnabled(True)
        item = self.hook_collection_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hook Collection"))
        item = self.hook_collection_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "No. of Hooks"))
        item = self.hook_collection_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Hook Collection Status"))
        item = self.hook_collection_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Hook Collection Execution Sequence"))
        __sortingEnabled = self.hook_collection_table.isSortingEnabled()
        self.hook_collection_table.setSortingEnabled(False)
        self.hook_collection_table.setSortingEnabled(__sortingEnabled)
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.add_new_collection_button.setText(_translate("MainWindow", "+Hook Collection"))
        self.edit_button.setText(_translate("MainWindow", "Edit"))
        self.hook_collection_search.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Search</span></p></body></html>"))
        self.hook_collection_search_input.setText(_translate("MainWindow", "Name of Hook Collection"))
        self.hook_collection_title.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Hook Collection View</span></p></body></html>"))