# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'figure6_createEditHookCollectionOverlay.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
<<<<<<< HEAD

class Ui_Dialog(object):
=======
from PyQt5.QtWidgets import QFileDialog, QDialog

class Ui_Dialog(QDialog):
>>>>>>> 0a03c38bf7576e965b526ecbfd32c6b2182de244
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(476, 321)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 461, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.verticalLayoutWidget.setFont(font)
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.verticalLayoutWidget)
        self.frame.setAutoFillBackground(True)
        self.frame.setStyleSheet("")
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setObjectName("frame")
        self.formLayout = QtWidgets.QFormLayout(self.frame)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_5 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.label_7 = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.lineEdit = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit.setFont(font)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.frame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setMaxVisibleItems(2)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalFrame = QtWidgets.QFrame(Dialog)
        self.horizontalFrame.setGeometry(QtCore.QRect(10, 170, 460, 114))
        self.horizontalFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_7.addWidget(self.label, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.checkBox_3 = QtWidgets.QCheckBox(self.horizontalFrame)
        self.checkBox_3.setEnabled(True)
        self.checkBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout_7.addWidget(self.checkBox_3)
        self.checkBox_2 = QtWidgets.QCheckBox(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout_7.addWidget(self.checkBox_2)
        self.checkBox = QtWidgets.QCheckBox(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout_7.addWidget(self.checkBox)
        self.verticalLayout_4.addLayout(self.verticalLayout_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.line = QtWidgets.QFrame(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line.setFont(font)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.comboBox_3 = QtWidgets.QComboBox(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setAutoFillBackground(False)
        self.comboBox_3.setMaxVisibleItems(2)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_3)
        self.comboBox_4 = QtWidgets.QComboBox(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setMaxVisibleItems(2)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_4)
        self.comboBox_5 = QtWidgets.QComboBox(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox_5.setFont(font)
        self.comboBox_5.setMaxVisibleItems(2)
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_5)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        self.line_2 = QtWidgets.QFrame(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.line_2.setFont(font)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout_2.addWidget(self.line_2)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_6.addWidget(self.label_3, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_6.setFont(font)
        self.lineEdit_6.setInputMask("")
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_6.addWidget(self.lineEdit_6)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_5.setFont(font)
        self.lineEdit_5.setInputMask("")
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_6.addWidget(self.lineEdit_5)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setInputMask("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_6.addWidget(self.lineEdit_4)
        self.horizontalLayout_2.addLayout(self.verticalLayout_6)
        self.verticalScrollBar_2 = QtWidgets.QScrollBar(self.horizontalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.verticalScrollBar_2.setFont(font)
        self.verticalScrollBar_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalScrollBar_2.setObjectName("verticalScrollBar_2")
        self.horizontalLayout_2.addWidget(self.verticalScrollBar_2)
        self.saveButton = QtWidgets.QPushButton(Dialog)
        self.saveButton.setGeometry(QtCore.QRect(310, 290, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saveButton.setFont(font)
        self.saveButton.setObjectName("saveButton")
        self.cancelButton = QtWidgets.QPushButton(Dialog)
        self.cancelButton.setGeometry(QtCore.QRect(390, 290, 71, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cancelButton.setFont(font)
        self.cancelButton.setObjectName("cancelButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.saveButton.clicked.connect(lambda:self.saveClicked())
        self.cancelButton.clicked.connect(lambda:self.cancelClicked())
        self.saveButton.clicked.connect(Dialog.accept)
        self.cancelButton.clicked.connect(Dialog.reject)

    def saveClicked(self):
        print("Save Clicked:")
        #print("Hook Collection Name:",self.lineEdit_3.text())
        #print("HC Description:",self.lineEdit_2.text())
        #print("Status",str(self.comboBox_2.currentText()))
        #print("Execution Sequence",self.lineEdit.text())
        #print(self)
        self.roiGroups = dict(HCName = str(self.lineEdit_3.text()),HCDescription = str(self.lineEdit_2.text()),HCStatus = str(self.comboBox_2.currentText()),HCExecutionSequence = str(self.lineEdit.text()))
        print(self.roiGroups)
        #self.accept

    def cancelClicked(self):
        print ("Cancel Clicked")

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_4.setText(_translate("Dialog", "Hook Collection Name"))
        self.label_5.setText(_translate("Dialog", "Description"))
        self.label_6.setText(_translate("Dialog", "Status"))
        self.label_7.setText(_translate("Dialog", "Execution Sequence"))
        self.lineEdit.setPlaceholderText(_translate("Dialog", "Enter Sequence No."))
        self.lineEdit_2.setPlaceholderText(_translate("Dialog", "Hook Collection Description"))
        self.lineEdit_3.setPlaceholderText(_translate("Dialog", "Hook Collection Name"))
        self.comboBox_2.setCurrentText(_translate("Dialog", "Enabled/Disabled"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "Enabled/Disabled"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "Enabled"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "Disabled"))
        self.label.setText(_translate("Dialog", "Hook"))
        self.checkBox_3.setText(_translate("Dialog", "Hook 1"))
        self.checkBox_2.setText(_translate("Dialog", "Hook 2"))
        self.checkBox.setText(_translate("Dialog", "Hook 3"))
        self.label_2.setText(_translate("Dialog", "Status"))
        self.comboBox_3.setCurrentText(_translate("Dialog", "Enabled/Disabled"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "Enabled/Disabled"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "Enabled"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "Disabled"))
        self.comboBox_4.setCurrentText(_translate("Dialog", "Enabled/Disabled"))
        self.comboBox_4.setItemText(0, _translate("Dialog", "Enabled/Disabled"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "Enabled"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "Disabled"))
        self.comboBox_5.setCurrentText(_translate("Dialog", "Enabled/Disabled"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "Enabled/Disabled"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "Enabled"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "Disabled"))
        self.label_3.setText(_translate("Dialog", "Hook Execution Sequence"))
        self.lineEdit_6.setPlaceholderText(_translate("Dialog", "Enter Sequence No."))
        self.lineEdit_5.setPlaceholderText(_translate("Dialog", "Enter Sequence No."))
        self.lineEdit_4.setPlaceholderText(_translate("Dialog", "Enter Sequence No."))
        self.saveButton.setText(_translate("Dialog", "Save"))
        self.cancelButton.setText(_translate("Dialog", "Cancel"))

