from PyQt5 import QtGui, QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget

class Hook_View(QWidget):

    def __init__(self, parent=None):
        QWidget.__init__(self, parent=parent)
        self.setObjectName("hook_page")
        self.frame_7 = QtWidgets.QFrame(self)
        self.frame_7.setGeometry(QtCore.QRect(0, 0, 871, 641))
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.FormName_2 = QtWidgets.QLabel(self.frame_7)
        self.FormName_2.setGeometry(QtCore.QRect(0, 0, 871, 51))
        self.FormName_2.setStyleSheet("background-color: rgb(75, 151, 226);\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"")
        self.FormName_2.setObjectName("FormName_2")
        self.TopFrame_2 = QtWidgets.QFrame(self.frame_7)
        self.TopFrame_2.setGeometry(QtCore.QRect(0, 50, 871, 631))
        self.TopFrame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TopFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TopFrame_2.setObjectName("TopFrame_2")
        self.frame_8 = QtWidgets.QFrame(self.TopFrame_2)
        self.frame_8.setGeometry(QtCore.QRect(30, 90, 771, 501))
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        
        self.hook_properties_label = QtWidgets.QLabel(self.frame_8)
        self.hook_properties_label.setGeometry(QtCore.QRect(10, 10, 741, 51))
        self.hook_properties_label.setStyleSheet("background-color: rgb(75, 151, 226);\n"
"font: 8pt \"MS Reference Sans Serif\";\n"
"")
        self.hook_properties_label.setObjectName("hook_properties_label")

        """ Hook table code """
        self.hook_table = QtWidgets.QTableWidget(self.frame_8)
        self.hook_table.setGeometry(QtCore.QRect(10, 60, 741, 421))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.hook_table.sizePolicy().hasHeightForWidth())
        self.hook_table.setSizePolicy(sizePolicy)
        self.hook_table.setMinimumSize(QtCore.QSize(741, 0))
        self.hook_table.setMaximumSize(QtCore.QSize(741, 16777215))
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        self.hook_table.setFont(font)
        self.hook_table.setStyleSheet("gridline-color: white;\n"
"border-right-color: white;\n"
"border-left-color: white;\n"
"\n"
"")
        self.hook_table.setLineWidth(1)
        self.hook_table.setMidLineWidth(1)
        self.hook_table.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.hook_table.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.hook_table.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.hook_table.setShowGrid(True)
        self.hook_table.setGridStyle(QtCore.Qt.SolidLine)
        self.hook_table.setCornerButtonEnabled(True)
        self.hook_table.setRowCount(6)
        self.hook_table.setObjectName("tableWidget_2")
        self.hook_table.setColumnCount(3)
        item = QtWidgets.QTableWidgetItem()
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../../tmp/mozilla_unknown0/CircularButton.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        item.setIcon(icon)
        self.hook_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon)
        self.hook_table.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon)
        self.hook_table.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon)
        self.hook_table.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon)
        self.hook_table.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setIcon(icon)
        self.hook_table.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        item.setFont(font)
        self.hook_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        item.setFont(font)
        self.hook_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("MS Reference Sans Serif")
        item.setFont(font)
        self.hook_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hook_table.setItem(0, 0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hook_table.setItem(0, 1, item)

        item = QtWidgets.QTableWidgetItem()
        self.hook_table.setItem(0, 2, item)

        item = QtWidgets.QTableWidgetItem()
        self.hook_table.setItem(1, 0, item)
        self.hook_table.horizontalHeader().setVisible(False)
        self.hook_table.horizontalHeader().setCascadingSectionResizes(False)
        self.hook_table.horizontalHeader().setDefaultSectionSize(150)
        self.hook_table.horizontalHeader().setSortIndicatorShown(False)
        self.hook_table.horizontalHeader().setStretchLastSection(True)
        self.hook_table.verticalHeader().setVisible(False)
        self.hook_table.verticalHeader().setCascadingSectionResizes(False)
        self.hook_table.verticalHeader().setDefaultSectionSize(40)
        self.hook_table.verticalHeader().setHighlightSections(True)
        self.hook_table.verticalHeader().setMinimumSectionSize(25)
        self.hook_table.verticalHeader().setSortIndicatorShown(True)
        self.hook_table.verticalHeader().setStretchLastSection(False)

        self.gridLayoutWidget_3 = QtWidgets.QWidget(self.TopFrame_2)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(30, 30, 821, 39))
        self.gridLayoutWidget_3.setObjectName("gridLayoutWidget_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")

        self.delete_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.delete_button.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(232, 232, 232)")
        self.delete_button.setObjectName("delete_button")
        self.gridLayout_7.addWidget(self.delete_button, 0, 2, 1, 1)

        self.add_hook_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.add_hook_button.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(232, 232, 232)")
        self.add_hook_button.setObjectName("add_hook_button")
        self.gridLayout_7.addWidget(self.add_hook_button, 0, 0, 1, 1)

        self.edit_button = QtWidgets.QPushButton(self.gridLayoutWidget_3)
        self.edit_button.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";\n"
"background-color: rgb(232, 232, 232)")
        self.edit_button.setObjectName("edit_button")
        self.gridLayout_7.addWidget(self.edit_button, 0, 1, 1, 1)
        
        self.Search_2 = QtWidgets.QLabel(self.gridLayoutWidget_3)
        self.Search_2.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";")
        self.Search_2.setObjectName("Search_2")
        self.gridLayout_7.addWidget(self.Search_2, 0, 4, 1, 1)
        
        self.search_edit = QtWidgets.QLineEdit(self.gridLayoutWidget_3)
        self.search_edit.setStyleSheet("font: 8pt \"MS Reference Sans Serif\";\n"
"color: rgb(179, 179, 179);\n"
"")
        self.search_edit.setObjectName("search_edit")
        self.gridLayout_7.addWidget(self.search_edit, 0, 5, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem2, 0, 3, 1, 1)

    def retranslateUI(self):
        _translate = QtCore.QCoreApplication.translate
        self.FormName_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Hook View</span></p></body></html>"))
        self.hook_properties_label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600;\">Hook Properties</span></p></body></html>"))
        self.hook_table.setSortingEnabled(True)
        item = self.hook_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hook"))
        item = self.hook_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Description"))
        item = self.hook_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Association to Hook Collection"))
        __sortingEnabled = self.hook_table.isSortingEnabled()
        self.hook_table.setSortingEnabled(False)
        self.hook_table.setSortingEnabled(__sortingEnabled)
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.add_hook_button.setText(_translate("MainWindow", "+Hook"))
        self.edit_button.setText(_translate("MainWindow", "Edit"))
        self.Search_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Search</span></p></body></html>"))
        self.search_edit.setText(_translate("MainWindow", "Name of Hook"))
