from PyQt5 import QtGui, QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget

class PCAP_View(QWidget):

    def __init__(self, parent=None):
        QWidget.__init__(self, parent=parent)
        self.setObjectName("pcap_page")
        self.pcap_page_frame = QtWidgets.QFrame(self)
        self.pcap_page_frame.setGeometry(QtCore.QRect(0, 0, 881, 641))
        self.pcap_page_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pcap_page_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pcap_page_frame.setObjectName("pcap_page_frame")
        self.layoutWidget1 = QtWidgets.QWidget(self.pcap_page_frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 881, 641))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.capture_filter_label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.capture_filter_label_2.setObjectName("capture_filter_label_2")
        self.gridLayout_3.addWidget(self.capture_filter_label_2, 3, 0, 1, 1)
        self.capture_filter_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.capture_filter_input.setText("")
        self.capture_filter_input.setObjectName("capture_filter_input")
        self.gridLayout_3.addWidget(self.capture_filter_input, 3, 1, 1, 6)

        self.capture_filter_apply_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.capture_filter_apply_2.setObjectName("capture_filter_apply_2")
        self.gridLayout_3.addWidget(self.capture_filter_apply_2, 3, 8, 1, 2)
        self.pcap_file_label = QtWidgets.QLabel(self.layoutWidget1)
        self.pcap_file_label.setObjectName("pcap_file_label")
        self.gridLayout_3.addWidget(self.pcap_file_label, 1, 0, 1, 1)
        self.capture_filter_cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.capture_filter_cancel.setObjectName("capture_filter_cancel")
        self.gridLayout_3.addWidget(self.capture_filter_cancel, 3, 10, 1, 1)
        self.packet_area_title = QtWidgets.QLabel(self.layoutWidget1)
        self.packet_area_title.setObjectName("packet_area_title")
        self.gridLayout_3.addWidget(self.packet_area_title, 4, 0, 1, 3)
        self.pcap_file_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pcap_file_input.setText("")
        self.pcap_file_input.setObjectName("pcap_file_input")
        self.gridLayout_3.addWidget(self.pcap_file_input, 1, 1, 1, 6)
        self.pcap_file_open = QtWidgets.QPushButton(self.layoutWidget1)
        self.pcap_file_open.setObjectName("pcap_file_open")
        self.gridLayout_3.addWidget(self.pcap_file_open, 1, 8, 1, 2)
        self.pcap_file_cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.pcap_file_cancel.setObjectName("pcap_file_cancel")
        self.gridLayout_3.addWidget(self.pcap_file_cancel, 1, 10, 1, 1)

        self.clear_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.clear_button.setObjectName("clear_button")
        self.gridLayout_3.addWidget(self.clear_button, 5, 9, 1, 2)
        self.field_area_label = QtWidgets.QLabel(self.layoutWidget1)
        self.field_area_label.setObjectName("field_area_label")
        self.gridLayout_3.addWidget(self.field_area_label, 6, 0, 1, 3)
        
        self.fuzz_area_label = QtWidgets.QLabel(self.layoutWidget1)
        self.fuzz_area_label.setObjectName("fuzz_area_label")
        self.gridLayout_3.addWidget(self.fuzz_area_label, 6, 6, 1, 1)

        self.capture_filter_title = QtWidgets.QLabel(self.layoutWidget1)
        self.capture_filter_title.setObjectName("capture_filter_title")
        self.gridLayout_3.addWidget(self.capture_filter_title, 2, 0, 1, 3)
        self.pcap_file_title = QtWidgets.QLabel(self.layoutWidget1)
        self.pcap_file_title.setObjectName("pcap_file_title")
        self.gridLayout_3.addWidget(self.pcap_file_title, 0, 0, 1, 2)

        self.get_packet_info_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.get_packet_info_button.setObjectName("get_packet_info_button")
        
        self.gridLayout_3.addWidget(self.get_packet_info_button, 12, 5, 1, 1)
        self.give_packet_info_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.give_packet_info_button.setObjectName("give_packet_info_button")
        self.gridLayout_3.addWidget(self.give_packet_info_button, 10, 5, 2, 1)
        
        self.stop_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.stop_button.setObjectName("stop_button")
        self.gridLayout_3.addWidget(self.stop_button, 13, 9, 1, 2)
        
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 14, 0, 1, 5)

        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 11, 8, 1, 3)
        
        self.selected_packet_name_label = QtWidgets.QLabel(self.layoutWidget1)
        self.selected_packet_name_label.setObjectName("selected_packet_name_label")
        self.gridLayout_3.addWidget(self.selected_packet_name_label, 7, 6, 1, 2)

        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 7, 8, 1, 3)

        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 9, 8, 2, 3)

        self.save_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.save_button.setObjectName("save_button")
        self.gridLayout_3.addWidget(self.save_button, 15, 2, 1, 1)

        self.drop_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.drop_button.setObjectName("drop_button")
        self.gridLayout_3.addWidget(self.drop_button, 15, 4, 1, 1)

        self.scrollArea_2 = QtWidgets.QScrollArea(self.layoutWidget1)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 406, 154))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.columnView_2 = QtWidgets.QColumnView(self.scrollAreaWidgetContents_5)
        self.columnView_2.setGeometry(QtCore.QRect(20, 10, 301, 192))
        self.columnView_2.setObjectName("columnView_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_3.addWidget(self.scrollArea_2, 7, 0, 7, 5)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 8, 6, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 9, 6, 1, 2)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_3.addWidget(self.lineEdit_7, 12, 8, 1, 3)
        
        self.fuzz_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.fuzz_button.setObjectName("fuzz_button")
        self.gridLayout_3.addWidget(self.fuzz_button, 13, 7, 1, 2)
        
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 8, 8, 1, 3)
        
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 12, 6, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 11, 6, 1, 2)

        self.forward_button = QtWidgets.QPushButton(self.layoutWidget1)
        self.forward_button.setObjectName("forward_button")
        self.gridLayout_3.addWidget(self.forward_button, 15, 3, 1, 1)

        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget1)
        self.tabWidget.setObjectName("tabWidget")

        """ Dissected tab """
        self.dissected_tab = QtWidgets.QWidget()
        self.dissected_tab.setObjectName("dissected_tab")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.dissected_tab)
        self.scrollArea_5.setGeometry(QtCore.QRect(10, 20, 691, 161))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 689, 159))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.listView_4 = QtWidgets.QListView(self.scrollAreaWidgetContents_6)
        self.listView_4.setGeometry(QtCore.QRect(0, 10, 256, 141))
        self.listView_4.setObjectName("listView_4")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.tabWidget.addTab(self.dissected_tab, "")

        """ Binary tab """
        self.binary_tab = QtWidgets.QWidget()
        self.binary_tab.setObjectName("binary_tab")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.binary_tab)
        self.scrollArea_6.setGeometry(QtCore.QRect(10, 20, 691, 161))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 689, 159))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.listView_5 = QtWidgets.QListView(self.scrollAreaWidgetContents_7)
        self.listView_5.setGeometry(QtCore.QRect(0, 10, 256, 141))
        self.listView_5.setObjectName("listView_5")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_7)
        self.tabWidget.addTab(self.binary_tab, "")

        self.hex_tab = QtWidgets.QWidget()
        self.hex_tab.setObjectName("hex_tab")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.hex_tab)
        self.scrollArea_7.setGeometry(QtCore.QRect(10, 20, 691, 161))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 689, 159))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.listView_6 = QtWidgets.QListView(self.scrollAreaWidgetContents_8)
        self.listView_6.setGeometry(QtCore.QRect(0, 10, 256, 141))
        self.listView_6.setObjectName("listView_6")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_8)
        self.tabWidget.addTab(self.hex_tab, "")
        self.gridLayout_3.addWidget(self.tabWidget, 5, 0, 1, 9)
    
    def retranslateUI(self):
        _translate = QtCore.QCoreApplication.translate
        self.capture_filter_label_2.setText(_translate("MainWindow", "Filter"))
        self.capture_filter_apply_2.setText(_translate("MainWindow", "Apply"))
        self.pcap_file_label.setText(_translate("MainWindow", "PCAP File"))
        self.capture_filter_cancel.setText(_translate("MainWindow", "Cancel"))
        self.packet_area_title.setText(_translate("MainWindow", "Packet Area"))
        self.pcap_file_open.setText(_translate("MainWindow", "Open"))
        self.pcap_file_cancel.setText(_translate("MainWindow", "Cancel"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))

        self.field_area_label.setText(_translate("MainWindow", "Field Area"))
        self.fuzz_area_label.setText(_translate("MainWindow", "Fuzzing Area"))
        self.capture_filter_title.setText(_translate("MainWindow", "CAPTURE FILTER"))
        self.pcap_file_title.setText(_translate("MainWindow", "PCAP FILE"))
        self.get_packet_info_button.setText(_translate("MainWindow", "->"))
        self.give_packet_info_button.setText(_translate("MainWindow", "<-"))
        self.stop_button.setText(_translate("MainWindow", "Stop"))
        self.label_16.setText(_translate("MainWindow", "Field Names, value, and display are editable fields."))
        self.selected_packet_name_label.setText(_translate("MainWindow", "Selected Packet Name"))
        self.save_button.setText(_translate("MainWindow", "Save Modification"))
        self.drop_button.setText(_translate("MainWindow", "Drop"))
        self.label_14.setText(_translate("MainWindow", "Selected Field Name"))
        self.label_9.setText(_translate("MainWindow", "Expected Return Type"))
        self.fuzz_button.setText(_translate("MainWindow", "Fuzz"))
        self.label_13.setText(_translate("MainWindow", "Maximum"))
        self.label_15.setText(_translate("MainWindow", "Minimum"))
        self.forward_button.setText(_translate("MainWindow", "Forward"))
        
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.dissected_tab), _translate("MainWindow", "Dissected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.binary_tab), _translate("MainWindow", "Binary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.hex_tab), _translate("MainWindow", "HEX"))
        self.tabWidget.setCurrentIndex(0)
