from PyQt5 import QtGui, QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget

class PCAP_View(QWidget):

    def __init__(self, parent=None):
        QWidget.__init__(self, parent=parent)
        self.setObjectName("pcap_page")
        self.pcap_page_frame = QtWidgets.QFrame(self)
        self.pcap_page_frame.setGeometry(QtCore.QRect(0, 0, 881, 641))
        self.pcap_page_frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pcap_page_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.pcap_page_frame.setObjectName("pcap_page_frame")
        self.layoutWidget1 = QtWidgets.QWidget(self.pcap_page_frame)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 0, 881, 641))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.capture_filter_label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.capture_filter_label_2.setObjectName("capture_filter_label_2")
        self.gridLayout_3.addWidget(self.capture_filter_label_2, 3, 0, 1, 1)
        self.capture_filter_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.capture_filter_input.setText("")
        self.capture_filter_input.setObjectName("capture_filter_input")
        self.gridLayout_3.addWidget(self.capture_filter_input, 3, 1, 1, 6)
        self.capture_filter_apply_2 = QtWidgets.QPushButton(self.layoutWidget1)
        self.capture_filter_apply_2.setObjectName("capture_filter_apply_2")
        self.gridLayout_3.addWidget(self.capture_filter_apply_2, 3, 8, 1, 2)
        self.pcap_file_label = QtWidgets.QLabel(self.layoutWidget1)
        self.pcap_file_label.setObjectName("pcap_file_label")
        self.gridLayout_3.addWidget(self.pcap_file_label, 1, 0, 1, 1)
        self.capture_filter_cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.capture_filter_cancel.setObjectName("capture_filter_cancel")
        self.gridLayout_3.addWidget(self.capture_filter_cancel, 3, 10, 1, 1)
        self.packet_area_title = QtWidgets.QLabel(self.layoutWidget1)
        self.packet_area_title.setObjectName("packet_area_title")
        self.gridLayout_3.addWidget(self.packet_area_title, 4, 0, 1, 3)
        self.pcap_file_input = QtWidgets.QLineEdit(self.layoutWidget1)
        self.pcap_file_input.setText("")
        self.pcap_file_input.setObjectName("pcap_file_input")
        self.gridLayout_3.addWidget(self.pcap_file_input, 1, 1, 1, 6)
        self.pcap_file_open = QtWidgets.QPushButton(self.layoutWidget1)
        self.pcap_file_open.setObjectName("pcap_file_open")
        self.gridLayout_3.addWidget(self.pcap_file_open, 1, 8, 1, 2)
        self.pcap_file_cancel = QtWidgets.QPushButton(self.layoutWidget1)
        self.pcap_file_cancel.setObjectName("pcap_file_cancel")
        self.gridLayout_3.addWidget(self.pcap_file_cancel, 1, 10, 1, 1)
        self.pushButton_18 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_3.addWidget(self.pushButton_18, 5, 9, 1, 2)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_12.setObjectName("label_12")
        self.gridLayout_3.addWidget(self.label_12, 6, 0, 1, 3)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_8.setObjectName("label_8")
        self.gridLayout_3.addWidget(self.label_8, 6, 6, 1, 1)
        self.capture_filter_title = QtWidgets.QLabel(self.layoutWidget1)
        self.capture_filter_title.setObjectName("capture_filter_title")
        self.gridLayout_3.addWidget(self.capture_filter_title, 2, 0, 1, 3)
        self.pcap_file_title = QtWidgets.QLabel(self.layoutWidget1)
        self.pcap_file_title.setObjectName("pcap_file_title")
        self.gridLayout_3.addWidget(self.pcap_file_title, 0, 0, 1, 2)
        self.pushButton_12 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_3.addWidget(self.pushButton_12, 12, 5, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_3.addWidget(self.pushButton_13, 10, 5, 2, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_3.addWidget(self.pushButton_17, 13, 9, 1, 2)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 14, 0, 1, 5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 11, 8, 1, 3)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 7, 6, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 7, 8, 1, 3)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 9, 8, 2, 3)
        self.pushButton_16 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_3.addWidget(self.pushButton_16, 15, 2, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_3.addWidget(self.pushButton_15, 15, 4, 1, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.layoutWidget1)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 406, 154))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.columnView_2 = QtWidgets.QColumnView(self.scrollAreaWidgetContents_5)
        self.columnView_2.setGeometry(QtCore.QRect(20, 10, 301, 192))
        self.columnView_2.setObjectName("columnView_2")
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout_3.addWidget(self.scrollArea_2, 7, 0, 7, 5)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_14.setObjectName("label_14")
        self.gridLayout_3.addWidget(self.label_14, 8, 6, 1, 2)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_9.setObjectName("label_9")
        self.gridLayout_3.addWidget(self.label_9, 9, 6, 1, 2)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_3.addWidget(self.lineEdit_7, 12, 8, 1, 3)
        self.pushButton_14 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_3.addWidget(self.pushButton_14, 13, 7, 1, 2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 8, 8, 1, 3)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_13.setObjectName("label_13")
        self.gridLayout_3.addWidget(self.label_13, 12, 6, 1, 2)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_15.setObjectName("label_15")
        self.gridLayout_3.addWidget(self.label_15, 11, 6, 1, 2)
        self.pushButton_19 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_3.addWidget(self.pushButton_19, 15, 3, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.layoutWidget1)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.scrollArea_5 = QtWidgets.QScrollArea(self.tab_4)
        self.scrollArea_5.setGeometry(QtCore.QRect(10, 20, 691, 161))
        self.scrollArea_5.setWidgetResizable(True)
        self.scrollArea_5.setObjectName("scrollArea_5")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 689, 159))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.listView_4 = QtWidgets.QListView(self.scrollAreaWidgetContents_6)
        self.listView_4.setGeometry(QtCore.QRect(0, 10, 256, 141))
        self.listView_4.setObjectName("listView_4")
        self.scrollArea_5.setWidget(self.scrollAreaWidgetContents_6)
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.scrollArea_6 = QtWidgets.QScrollArea(self.tab_5)
        self.scrollArea_6.setGeometry(QtCore.QRect(10, 20, 691, 161))
        self.scrollArea_6.setWidgetResizable(True)
        self.scrollArea_6.setObjectName("scrollArea_6")
        self.scrollAreaWidgetContents_7 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_7.setGeometry(QtCore.QRect(0, 0, 689, 159))
        self.scrollAreaWidgetContents_7.setObjectName("scrollAreaWidgetContents_7")
        self.listView_5 = QtWidgets.QListView(self.scrollAreaWidgetContents_7)
        self.listView_5.setGeometry(QtCore.QRect(0, 10, 256, 141))
        self.listView_5.setObjectName("listView_5")
        self.scrollArea_6.setWidget(self.scrollAreaWidgetContents_7)
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.scrollArea_7 = QtWidgets.QScrollArea(self.tab_6)
        self.scrollArea_7.setGeometry(QtCore.QRect(10, 20, 691, 161))
        self.scrollArea_7.setWidgetResizable(True)
        self.scrollArea_7.setObjectName("scrollArea_7")
        self.scrollAreaWidgetContents_8 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_8.setGeometry(QtCore.QRect(0, 0, 689, 159))
        self.scrollAreaWidgetContents_8.setObjectName("scrollAreaWidgetContents_8")
        self.listView_6 = QtWidgets.QListView(self.scrollAreaWidgetContents_8)
        self.listView_6.setGeometry(QtCore.QRect(0, 10, 256, 141))
        self.listView_6.setObjectName("listView_6")
        self.scrollArea_7.setWidget(self.scrollAreaWidgetContents_8)
        self.tabWidget.addTab(self.tab_6, "")
        self.gridLayout_3.addWidget(self.tabWidget, 5, 0, 1, 9)
    
    def retranslateUI(self):
        _translate = QtCore.QCoreApplication.translate
        self.capture_filter_label_2.setText(_translate("MainWindow", "Filter"))
        self.capture_filter_apply_2.setText(_translate("MainWindow", "Apply"))
        self.pcap_file_label.setText(_translate("MainWindow", "PCAP File"))
        self.capture_filter_cancel.setText(_translate("MainWindow", "Cancel"))
        self.packet_area_title.setText(_translate("MainWindow", "Packet Area"))
        self.pcap_file_open.setText(_translate("MainWindow", "Open"))
        self.pcap_file_cancel.setText(_translate("MainWindow", "Cancel"))
        self.pushButton_18.setText(_translate("MainWindow", "Clear"))
        self.label_12.setText(_translate("MainWindow", "Field Area"))
        self.label_8.setText(_translate("MainWindow", "Fuzzing Area"))
        self.capture_filter_title.setText(_translate("MainWindow", "CAPTURE FILTER"))
        self.pcap_file_title.setText(_translate("MainWindow", "PCAP FILE"))
        self.pushButton_12.setText(_translate("MainWindow", "->"))
        self.pushButton_13.setText(_translate("MainWindow", "<-"))
        self.pushButton_17.setText(_translate("MainWindow", "Stop"))
        self.label_16.setText(_translate("MainWindow", "Field Names, value, and display are editable fields."))
        self.label_7.setText(_translate("MainWindow", "Selected Packet Name"))
        self.pushButton_16.setText(_translate("MainWindow", "Save Modification"))
        self.pushButton_15.setText(_translate("MainWindow", "Drop"))
        self.label_14.setText(_translate("MainWindow", "Selected Field Name"))
        self.label_9.setText(_translate("MainWindow", "Expected Return Type"))
        self.pushButton_14.setText(_translate("MainWindow", "Fuzz"))
        self.label_13.setText(_translate("MainWindow", "Maximum"))
        self.label_15.setText(_translate("MainWindow", "Minimum"))
        self.pushButton_19.setText(_translate("MainWindow", "Forward"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "Dissected"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Binary"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("MainWindow", "HEX"))
        self.tabWidget.setCurrentIndex(0)